### ISSUE TITLE
Tenant Support

### ISSUE THREAD

**Issue by marcrib** [aruss/IdentityBase#18]
I have 2 products / applications
I would like to create an SSO for my users.
But for each application,  needs a TenantId to filter information in the database

Any idea? Solution?

**Comment by aruss** [comment]
If you want SSO for two application then it is already there, you just run a idsrv once and add two clients, the user then will be able to log in both applications with the same account, and if you implement your PR properly the whole SSO thing will just work. 

But if you want to have separate sets of users, like user with the same email but different passwords for different PRs then you have to run the idsrv twice.

The current design is not meant to be able to handle tenants. It's more, one idsrv for one project with multiple clients. If you still want to do it, you could run the idsrv multiple times, one for each tenant with own sub domain, custom sub domains would also separate authentication cookies, but then its not SSO.

There is a idea for the future, to add a tenant functionality to it, then there will be users and clients assigned to it, the idea is that the user can share this credentials across all tenants but if a tenant whats to see all users he will just see all the users who is assigned to his clients.
